[package]
name = "proxy"
version = "0.0.1"
authors = ["bytesnake <bytesnake@mailbox.org>"]

[dependencies]
libc = "0.2.42"
nix = "0.11"
memmap = "0.6"
elf = "0.0.10"
errno = "0.2.4"
inotify = "0.5"
byteorder = "1"
log = "0.4"
env_logger = "0.5.10"
chan-signal = "0.3.1"
raw-cpuid = "5.0.0"
